CREATE TABLE tb_fornecedor (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    cnpj VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    endereco VARCHAR(255) NOT NULL
);

